BackendBundle\Entity\Product:
    type: entity
    table: products
    indexes:
        fk_products_users:
            columns:
                - user_id
        fk_products_categories:
            columns:
                - category_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        productName:
            type: string
            nullable: true
            length: 20
            options:
                fixed: false
            column: product_name
        description:
            type: string
            nullable: true
            length: 1000
            options:
                fixed: false
        image:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        available:
            type: string
            nullable: true
            length: 5
            options:
                fixed: false
        price:
            type: decimal
            nullable: true
            precision: 9
            scale: 2
        createdAt:
            type: datetime
            nullable: true
            column: created_at
        updatedAt:
            type: datetime
            nullable: true
            column: updated_at
    manyToOne:
        category:
            targetEntity: Categorie
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                category_id:
                    referencedColumnName: id
            orphanRemoval: false
        user:
            targetEntity: User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
